### ISSUE TITLE
Turbo breaks audio loading

### ISSUE THREAD

**Issue by zany130** [AdmiralCurtiss/SenPatcher#103]
Holding turbo in some situations such as retrying a battle causes the audio not to load

**Comment by AdmiralCurtiss** [comment]
Please specify which game you're talking about. But I assume this is a duplicate of #1 or #54 (haven't confirmed if CS4 has this bug).

**Comment by zany130** [comment]
sorry was still half-asleep when I wrote this lol. its CS3 and I thought I saw an issue for this already but couldn't find so yup its a duplicate I'll go ahead and close this
