### ISSUE TITLE
Kuro no Kiseki - modifying monster stats

### ISSUE THREAD

**Issue by Arachno67** [AdmiralCurtiss/SenPatcher#112]
Hi again!

I am not sure if this is the right place to ask the following question but I have no idea who else or where else I could turn to ;)

In CS1 to CS4 I managed to hexedit monster stats with some research and some trial and error but looking at Kuro no Kiseki’s t_status.tbl (attached) I am at a complete loss. Hajimari had abyss difficulty which felt quite right.

As Kuro is too easy, could you please tell me how/where exactly I can modify **HP**, **STR**, **DEF**, **ATS**, **ADF** and **SPD** for all monsters on nightmare difficulty?! I suppose that there are some modifiers for **player damage** and **enemy damage** as well.

Any kind of help would be highly appreciated, it would be great if I at least understood how to increase HP, SPD and enemy damage for nightmare difficulty!

[t_status.zip](https://github.com/AdmiralCurtiss/SenPatcher/files/10240778/t_status.zip)

**Comment by AdmiralCurtiss** [comment]
Not exactly my area of expertise. I don't have a copy of Kuro to test/experiment with this, either (nor do I want one until the official English release). You might have better luck asking the people who do difficulty mods of the CS games.

**Comment by AdmiralCurtiss** [comment]
Maybe try over here: https://discord.gg/R6KBuuaP4X

**Comment by Arachno67** [comment]
Understood, I'll try my luck over there, thanks!
