### ISSUE TITLE
CS1/2/3: Lipflaps desync when in turbo mode. (only the timed ones, the untimed ones work fine)

### ISSUE THREAD

**Issue by AdmiralCurtiss** [AdmiralCurtiss/SenPatcher#115]
This is already working correctly in CS4.

I assume all we need to do here is to find the lipflap function and pass it the unscaled time instead of the scaled one.

**Comment by AdmiralCurtiss** [comment]
Probably related: Active voices (the mini-skits in the corner of the screen while running around) start overlapping in CS1/2/3 in turbo, but in CS4 they time properly even in turbo.

**Comment by richardziegler** [comment]
Adding comment from AdmiralCurtiss in #25: 

> I think it's the function at 0x5780e0 that you're searching for -- that is, for https://github.com/AdmiralCurtiss/SenPatcher/issues/115. If I'm interpreting this correctly, that function returns at any given timepoint whether the mouth should be animating or not.

> equivalent code in all the games, I think:
> CS1: 0x5f8750
> CS2: 0x5780e0
> CS3: ~0x140317832
> CS4: ~0x1402f8e22

**Comment by richardziegler** [comment]
Moving over here to keep the comments about this issue in the right thread.

Do you think we have the `TurboFactorField` value saved anywhere in data? I assume this is the default value we pass if turbo is enabled.

In CS2 at `0x6d03cd` it pushes (I think a string?) to the stack. Some of the code around it looks like it was from the SenLauncher though. So I am unsure of it's relevance.

**Comment by richardziegler** [comment]
> CS2: 0x5780e0

I followed `0x5780e0` in the debugger today and did not see anything that indicated a specific int being passed in to represent the factor of turbo I had chosen in the SenLauncher settings. I would assume this would be a constant saved somewhere once it's value is loaded in from settings.xml. Makes it easy to multiply the speed things are running at without having to read it over and over. But I could very well be making a bad assumption here.

Things I  did notice - this breakpoint was hit in the debugger whenever a scene for talking happened and whenever a character would do one of their idle animations. That is to say that while the mouths move during field attacks and party leader changes - it does not call this function.

**Comment by AdmiralCurtiss** [comment]
I looked at this a bit more today, some notes (CS2):

The first parameter to the function at `0x5780e0` is the position (in milliseconds, from the start of the voice clip) of the lipflap to look up. This is loaded at `0x57acc6` and is stored as a float (in seconds) at that referenced location (the `EDI + ESI*0x8 + 0x1028` there).

If you trace that memory location backwards to where it's written, you get to `0x5827b1`; this function gets the timestep this frame as its float parameter, already scaled by the turbo factor if turbo is active. You can trace this even further back (loaded at `0x557c90`, written at `0x5822d1`, loaded at `0x5822ca`, written at `0x4136fc`) to arrive at `0x4136da` for the function call that scales it if turbo is active. (there's also a clamp here and weirdly the clamp happens after the turbo scale?)

Next step would be experimenting here what we can do to pass the unscaled timestep down without breaking actual turbo functionality. Probably the best we can do here is to store the unscaled value in a global somewhere and use it in specific spots, anything else seems like a nightmare to modify the ASM for...

**Comment by richardziegler** [comment]
Progress!! I finally finished CS2 so my short break from the mod is over. I want to take a look at this a bit today and explore your findings.

**Comment by AdmiralCurtiss** [comment]
This is fixed in SenPatcher v1.2
