### ISSUE TITLE
CS1: Minor dialogue error in Chapter 3.

### ISSUE THREAD

**Issue by imchau** [AdmiralCurtiss/SenPatcher#12]
Under `\data\scripts\scena\dat_us\t1000.dat` there is a text bug on PC that was fixed on PS4. It concerns one line by Alisa in Chapter 3 talking about the upcoming midterm exams as if they were already finished.

PC: http://trailsinthedatabase.com/game-scripts?game_id=6&fname=t1000#897
> Anyway, how do you think you
> did on the exams?

PS4: https://youtu.be/sM5pF37rcIk?t=1167
> Anyway, how do you feel? All
> prepped and ready for our exams?

It would be good if a way to address this somehow could be found.

This is complicated by the fact that it's a voiced line. To have matching audio, it would need to be ripped because the updated audio is most likely not included on PC.

The scena will need to be recompiled to match PS4, because the text length exceeds the original on PC, so it's not easily hex editable. An alternative is to simply hex edit it anyway within the current string limits, but the problem with mismatching the audio remains.

**Comment by AdmiralCurtiss** [comment]
Huh, that's interesting, didn't know they did any voice line changes for the PS4 version. Is this the only known one or are there others too?

**Comment by imchau** [comment]
> 
> 
> Huh, that's interesting, didn't know they did any voice line changes for the PS4 version. Is this the only known one or are there others too?
It's the only one I'm aware of, since it's an easy-to-notice error on PC. I checked that instance with PS4 since I didn't recall it there.

Also, you may have [seen this, but it confirms the low likelihood for an official patch](https://www.reddit.com/r/Games/comments/eq6qpv/ama_im_peter_durante_thoman_modder_dsfix_creator/feo9tg0/) to fix some of these for CS 1 and 2 on PC.

On the other hand, according to NISA some widely reported bugs with CS3 are "on their radar", so it's likely another update will come out eventually.

**Comment by AdmiralCurtiss** [comment]
Okay yeah script fix was easy enough, see 3ebcf5e51d07d12de7eb26426fe2c56e10400d8c. No idea what we do with the audio though.

**Comment by imchau** [comment]
I'm not sure if you were aware but there are a number of tools to handle Falcom's scena files, especially for older titles like Sky and Crossbell. Not sure about the status of tools for Cold Steel, but the format is very, very similar. https://github.com/ZhenjianYang/EDDecompiler

**Comment by AdmiralCurtiss** [comment]
Yeah I have seen that, and you're right, those formats are definitely similar, but there's no actual opcode table for the CS games in there. But yes, worth looking into if you need to do something more complicated than just editing a line.

**Comment by AdmiralCurtiss** [comment]
Reminder to self: If we replace the voice file, don't forget to also adjust the lipsync timing if we can figure that out.

**Comment by AdmiralCurtiss** [comment]
Other voice file differences and oddities:

`e8v00213` has a nonstandard header, check if the game actually plays this one correctly.
`e8v00540` was changed from PC ('uh... right') to PS4 ('ah...') (TODO: where is this?)
`e8v04585` is super weird. On PC before patch 1.3 it was Emma going 'Maybe I still have a ways to go before I fully understand the whole class system here.', which seems like a mistranslation. Then in 1.3 it was changed to 'I may not always show much in the way of class spirit.', which, yeah sure. But then the PS4 version uses the old line again! What?
`pc8v02551` is the Alisa line here.
`pc8v10286` was accidentally overwritten in PC update 1.6 with a completely different line; PS4 has the pre-1.6 file as `pc8v10286` and the 1.6 line as `pc8v10286_6`, while my fix (see #32) has the 1.6 file at `pc8v10286` and the pre-1.6 one as `pc8v10299`.

**Comment by AdmiralCurtiss** [comment]
v0.6 is released now, which includes the full fix for this, including the voice clip!
