### ISSUE TITLE
SHA1 CS2 x2 (dlc ?)

### ISSUE THREAD

**Issue by Klemci** [AdmiralCurtiss/SenPatcher#122]
ERROR: Couldn't find base file with hash
3d75d79e3201f8f5ac61c206f8cc86db7c4651dd
ace845b437df94fbfe2d638a2ec162b492a657b3

I can only think about this files being part of a dlc, no ?

**Comment by AdmiralCurtiss** [comment]
Those are the `dat\t1001.dat` and `dat_us\t1001.dat` of CS2 version 1.4, ie [before the 1.4.1 patch that fixed some NG+ carryovers](https://steamcommunity.com/app/748490/eventcomments/1636418037462919987). Can you be more specific what you're trying to do?

**Comment by Klemci** [comment]
I try to patch my game, files are not listed, just their SHA1 (for this two), i'll find the files, i already found one mistypen by installer in CS1 (ed8éŹ2123 was ed8ｍ2123 WAV) !

**Comment by AdmiralCurtiss** [comment]
Yeah there's a few files with non-ASCII filenames in CS1 and CS2 that aren't properly uploaded/packed in all distributions. SenPatcher tries to fix those when you open a game.

See also https://github.com/AdmiralCurtiss/SenPatcher/blob/master/SenLib/FilenameFix.cs

**Comment by AdmiralCurtiss** [comment]
(I'm still not sure what your actual issue here is btw)

**Comment by Klemci** [comment]
I have no file(s) with this hashes (at all)

3d75d79e3201f8f5ac61c206f8cc86db7c4651dd
ace845b437df94fbfe2d638a2ec162b492a657b3

**Comment by AdmiralCurtiss** [comment]
Yeah if you have CS2 1.4.1 or 1.4.2 that's normal. Downgrade to CS2 1.4 to find them (on Steam it's under Properties -> Betas, on GoG there's an option to switch to an older version somewhere in GoG Galaxy).

**Comment by Klemci** [comment]
OKay, allright...

![Capture](https://github.com/AdmiralCurtiss/SenPatcher/assets/90113078/c940b962-c6f0-4ad4-aff2-20e1dd45da34)

**Comment by AdmiralCurtiss** [comment]
Oh that's weird, that shouldn't happen. If that's actually preventing you from using the patcher there's a bug somewhere.

**Comment by Klemci** [comment]
Patcher patched CS1-3-4 already flawlessly, only CS2 (v1.4.1) fails.

**Comment by AdmiralCurtiss** [comment]
Can you upload the log file? (`senpatcher.log`)

**Comment by Klemci** [comment]
It's huge, i used the messages to get files listed only needed for patching, so i launched it more than once or two times (by game)...

[senpatcher.log](https://github.com/AdmiralCurtiss/SenPatcher/files/13464779/senpatcher.log)

**Comment by AdmiralCurtiss** [comment]
```
[C:\SenPatcher\SenLib\FileStorage.cs:135 InitializeFromKnownFiles()] Trying acquisition from file at Y:\9700F\Legend of Heroes\0MOD\COLD_EXE_senpatched\Cold Steel II\data/scripts/scena/dat_us/t1001.dat...
[C:\SenPatcher\SenLib\FileStorage.cs:157 InitializeFromKnownFiles()] File data/scripts/scena/dat_us/t1001.dat does not exist.
```

Your t1001.dat is missing completely, something definitely went wrong with your install there. Please redownload the game from wherever you bought it and try again. I'll see if I can improve the error message for such cases.

**Comment by Klemci** [comment]
This ones, are here 👍 
bin\Win32\ed8_2_PC_JP.exe                 6,069 MB
bin\Win32\ed8_2_PC_US.exe                 6,085 MB
data\scripts\book\dat_us\book00.dat      49,930 KB
data\scripts\book\dat_us\book01.dat      70,032 KB
data\scripts\book\dat_us\book02.dat     185,313 KB
data\scripts\book\dat_us\book03.dat      17,548 KB
data\scripts\book\dat_us\book04.dat      50,209 KB
data\scripts\book\dat_us\book05.dat      54,817 KB

data\scripts\scena\dat\t1001.dat        171,329 KB

data\scripts\scena\dat_us\e7060.dat     157,798 KB
data\scripts\scena\dat_us\e7090.dat     129,415 KB
data\scripts\scena\dat_us\e7101.dat      66,235 KB
data\scripts\scena\dat_us\e7110.dat     162,712 KB
data\scripts\scena\dat_us\r1010.dat      28,610 KB

data\scripts\scena\dat_us\t0001.dat     120,978 KB

data\scripts\scena\dat_us\t0010.dat      30,438 KB
data\scripts\scena\dat_us\t1010.dat     480,204 KB
data\scripts\scena\dat_us\t3060.dat      38,657 KB
data\scripts\scena\dat_us\t3500.dat     152,548 KB
data\scripts\scena\dat_us\t4000.dat     388,743 KB
data\scripts\scena\dat_us\t4080.dat     159,462 KB
data\scripts\scena\dat_us\t5501.dat     109,259 KB
data\scripts\scena\dat_us\t6500.dat      79,915 KB
data\scripts\talk\dat_us\tk_rosine.dat   12,853 KB
data\text\dat_us\t_item.tbl             186,792 KB
data\text\dat_us\t_magic.tbl             60,048 KB
data\text\dat_us\t_notecook.tbl           6,681 KB
data\text\dat_us\t_voice.tbl            530,353 KB
Sen2Launcher.exe                        559,500 KB
--------------------------------------------------
29 Fichiers - 16,120 MB

**Comment by Klemci** [comment]
One of the two (dat folder, not _us) i added by finding it by sha1.

**Comment by Klemci** [comment]
Worked,

sorry, i've been finding files by sha1 and thinked i missed one. Fianlly.

**Comment by Klemci** [comment]
Great tool, thanks for the hard work done on the games.
