### ISSUE TITLE
CS1: Error removing animation skip for Turbo

### ISSUE THREAD

**Issue by SanbikiNoKaeru** [AdmiralCurtiss/SenPatcher#125]
![image](https://github.com/AdmiralCurtiss/SenPatcher/assets/96570864/55b560cb-8a51-4025-ba6c-3701a4596e2a)
It's a freshly installed game. Run as administrator.
![image](https://github.com/AdmiralCurtiss/SenPatcher/assets/96570864/9bad9a6f-98bf-4e3a-ad3d-0d8e6452fc83)
Everything else is installing no problems it looks like except removing animation skip, which is a pity because that's the reason I downloaded this patch for.

**Comment by AdmiralCurtiss** [comment]
Based on the error message I think it's just failing to find a clean copy of the executable, try running a file verification in Steam.

If that's not it then please post the log file.

**Comment by AdmiralCurtiss** [comment]
Possibly also some process is holding a handle on the executable, you can try restarting your computer.

**Comment by SanbikiNoKaeru** [comment]
> Possibly also some process is holding a handle on the executable, you can try restarting your computer.

Yes, that was it for some reason ED8.exe was running for no reason, from the time I test launched the game probably. 
![image](https://github.com/AdmiralCurtiss/SenPatcher/assets/96570864/3b38d230-1222-4cd1-8c68-e96806ff2f7b)
Resolved now, thanks!
