### ISSUE TITLE
CS1: Missing sound effect files.

### ISSUE THREAD

**Issue by imchau** [AdmiralCurtiss/SenPatcher#13]
Since the changelog mentions fixing audio issues and missing SFX in CS2, I thought this was worth a mention.

> When Olivert makes his entrance during the party's meeting with Alfin at Saint Astraia, the lute strum sound effect isn't played. (despite the entire party acknowledging it) The lute strum is the exact same effect Olivert used in the Trails in the Sky games to make his entrance, and it did play in the console versions, so having it missing takes a beloved wink to the Sky games out of the scene. 
Source: https://steamcommunity.com/app/538680/discussions/0/1471967615847224280/?ctp=8#c1473095331502603214

PS4 video with working sound effect: https://youtu.be/yugxNGKKQFU?t=1014

**Comment by AdmiralCurtiss** [comment]
The CS2 sound effect fix was more of a byproduct of the audio timing fixes -- I think what happens is that the game refuses to re-play the same sound effect before it finished playing, and the previous audio timing didn't 'finish' the first effect in time, or something along those lines. So this is almost definitely something different.

Still, good to have a note on this.

**Comment by AdmiralCurtiss** [comment]
lol I think this asset is just missing in the PC version for some reason. The sound affect it attempts to play is `data\se\wav\ed8m4217.wav` but if you look that file doesn't exist. Probably a reasonably easy fix then...

**Comment by AdmiralCurtiss** [comment]
While I'm here, in case it's relevant at some point: Comparing with the PS3 assets, `ed8m2150` and `ed8m4097` are also missing. Also `ed8ｍ2123` has a nonstandard unicode `m` in its filename.

**Comment by AdmiralCurtiss** [comment]
`ed8m4097` is part of a swoosh sound effect in a scene in Heimdallr Port when Phantom Thief B reveals himself, which is weirdly enough like *right before* the scene with the missing lute sound.

**Comment by AdmiralCurtiss** [comment]
`ed8m2150` is an ambient noise inside the Courageous.

**Comment by AdmiralCurtiss** [comment]
Unclear if `ed8ｍ2123` is used at all, or at the very least I can't find it being used in any scenario script file.

**Comment by AdmiralCurtiss** [comment]
In CS2 the files `ed8u0000` (0x0fa0) through `ed8u0007` (0x0fa7) exist on PS3 but not PC, but those very much sound like test/dummy sound effects to me so probably not a problem there.

**Comment by AdmiralCurtiss** [comment]
This should be fixed as of beta5.
