### ISSUE TITLE
Making a 'mod' out of files

### ISSUE THREAD

**Issue by SanbikiNoKaeru** [AdmiralCurtiss/SenPatcher#135]
I'm not a modder but I need to make a .p3a file out of CS2 difficulty mod so it would work properly.
https://mega.nz/file/0eYXCSIZ#7FeFhmS3nD16snT9sdCSe6cETO3UXyydAh6ODde4MFY
(changes 6 files in data\text\dat_us\)
How can I do it?

**Comment by AdmiralCurtiss** [comment]
Put the `data` folder into an otherwise empty directory and then run `sentools.exe P3A.Pack` on it.

But since this is easy enough, here: 
[[ToCS2] Difficulty-Balance mod - Live v1.0.zip](https://github.com/user-attachments/files/16203336/ToCS2.Difficulty-Balance.mod.-.Live.v1.0.zip)

**Comment by SanbikiNoKaeru** [comment]
It works, thank you very much.
