### ISSUE TITLE
CS2: Music queueing still bugs out sometimes. (Skips enqueueing track it should.)

### ISSUE THREAD

**Issue by AdmiralCurtiss** [AdmiralCurtiss/SenPatcher#14]
I thought I fixed this with #6 but I guess not. I felt like I ran into this once on an back-and-forth area transition, which I chalked up to me not paying attention cause I failed to reproduce it, but a comment on reddit claims that the Intermission track didn't play in one of their tries, which I have no reason to disbelieve at the moment.

So I guess I'll have to figure out what part of the logic breaks here. I mean, I realized the code wasn't foolproof, but I thought the problem was the other way around; ie, it would enqueue more than it should, not less than it should.

Alternatively, maybe I'm approaching this from the wrong end, maybe we should just always enqueue like in my first fix attempt (which did reliably fix the parts where it didn't switch the track) but catch enqueues of the playing track on the audio thread side and skip the playing part there. That way our actual bgm playing state should always be available and correct.

**Comment by soundersfan84** [comment]
That was me that mention about 1 of the tries with the intermission music not playing but the later 3 tries and it played fine. I'll do futher testing and see what was different between try 1 and 4 which was both with turbo mode on with that dialogue sequence try 2 amd 3 was with out turbo mode and it worked fine.  Maybe i held on turbo mode going to the battle fight before letting go on try one. Ill get back to you after more testing.

**Comment by AdmiralCurtiss** [comment]
Feel free to attempt to figure this out, but I suspect you won't get very far without a debugger. It very much sounds like a race condition between the main thread and the audio thread to me.

**Comment by soundersfan84** [comment]
well after going through several more times with turbo mode the music did play.  So who know why try 1 didn't but the rest of them did. Either way what you adjusted did the trick with the patch. The fans who had that missing music issue my self included we thx you.

**Comment by AdmiralCurtiss** [comment]
Alright, I wrote a new check for this on the audio thread side instead of the main thread side. I've tested known issue cases (pinch BGM in boss fights without one, places where the dungeon music keeps playing in battle) and they work fine so I hope this is a solid fix now. I'll play with it for a day or two to see if I run into any obvious problems and then push a beta4 if it checks out.

**Comment by AdmiralCurtiss** [comment]
Hopefully fixed in beta4: https://github.com/AdmiralCurtiss/SenPatcher/releases/tag/beta4
