### ISSUE TITLE
CS2 Freeze timer

### ISSUE THREAD

**Issue by SleepEmperorAlucard** [AdmiralCurtiss/SenPatcher#148]
The in-game timer is no longer working when you use the senpatcher 1.2, is working in 1.1.1.

**Comment by AdmiralCurtiss** [comment]
Also please check if it's still broken if you set:

```
AdjustTimersForTurbo=false
```

in `senpatcher_settings.ini`.

**Comment by AdmiralCurtiss** [comment]
Since I have not gotten any feedback, I'll assume this is the same as #147, which is fixed in v1.2.1
