### ISSUE TITLE
Linux: senpatcher fails to patch the GOG version installed through lutris

### ISSUE THREAD

**Issue by MartinF99** [AdmiralCurtiss/SenPatcher#151]
When trying to patch cold steel 2 on the GOG version the patcher fails with an error message that DINPUT8.dll could not be found in the necessary path, despite copying over the file from Senpatchers directory. 
Error MEssage: "Could not find part of path /home/USERNAME/Games/gog/the-legend-of-heroes-trails-of-cold-steel/drive_c/GOG Games/The Legend Of Heroes Trails of Cold Steel II/bin/Win32/DINPUT8.dll"

**Comment by AdmiralCurtiss** [comment]
I'm not sure how Lutris works but did you add the `WINEDLLOVERRIDES=DINPUT8=n,b` environment variable as mentioned in the Linux/Steam Deck section of the readme?
