### ISSUE TITLE
no .exe on download??

### ISSUE THREAD

**Issue by ArkaneDaywalker** [AdmiralCurtiss/SenPatcher#30]
When I download the latest version of the beta, there aren't any .exe files. There are .cs files and .csproj files 

I'm not very well versed in code, I just want to play replay cold steel without the bad version of turbo mode

**Comment by AdmiralCurtiss** [comment]
You want the `*.7z` file from over here, under the Assets dropdown: https://github.com/AdmiralCurtiss/SenPatcher/releases

**Comment by ArkaneDaywalker** [comment]
Okay, so i did that and it'll only open in notepad

**Comment by ArkaneDaywalker** [comment]
Finaly figured it out, thank you for your help!
