### ISSUE TITLE
CS2: Imperial Chronicle Issue 3 mistranslation

### ISSUE THREAD

**Issue by imchau** [AdmiralCurtiss/SenPatcher#37]
The title of the last article in Imperial Chronicle Issue 3 from CS2 didn't make much sense in the narrative:
> [Incident] A Strange Knight Appears in the West?

Double-checking with the original Japanese text:
> 【事件】東部に謎の《騎士》現る？

Should therefore it should be:
> [Incident] A Strange Knight Appears in the East?

**Comment by AdmiralCurtiss** [comment]
Yup, I'll have to agree, that does look like a straight up error. Easy enough to fix.

**Comment by AdmiralCurtiss** [comment]
![20210103031536_1](https://user-images.githubusercontent.com/4522237/103470382-0165ee80-4d72-11eb-85fe-ba3162b30a9e.jpg)

**Comment by AdmiralCurtiss** [comment]
v0.6 is released now, which includes this fix.
