### ISSUE TITLE
CS1: Minor typo on Crescent Mirror

### ISSUE THREAD

**Issue by onmyouji** [AdmiralCurtiss/SenPatcher#65]
Hi,

I noticed other rare quartz has (R) in front of their description, but there's none on Crescent Mirror R.

![20210806042449_1](https://user-images.githubusercontent.com/8424198/128423819-7115d04f-5411-490c-a5b4-49a154479918.jpg)

![20210806042512_1](https://user-images.githubusercontent.com/8424198/128423901-6f2126d6-a5d6-4969-8d2a-a8b67eab566e.jpg)

**Comment by AdmiralCurtiss** [comment]
![20210823052600_1](https://user-images.githubusercontent.com/4522237/130386177-8a3e07a0-c40b-4e8b-945e-31bd58906304.jpg)

Not gonna push a new release for just this but just so you know, I've fixed this.

CS1 and 2 probably could use a item description consistency pass like 6cac4ac759da1b793c0a966ac08d03bbc57ae8cb, too...

**Comment by AdmiralCurtiss** [comment]
Fixed in [v0.8](https://github.com/AdmiralCurtiss/SenPatcher/releases/tag/v0.8).
