### ISSUE TITLE
Make the patcher compatible with older version

### ISSUE THREAD

**Issue by zemanyak** [AdmiralCurtiss/SenPatcher#69]
Hello,

Would it be possible to make the patcher compatible with earlier builds ? I have CS2 v1.3 and cannot currently update to 1.4.x so it's a bit frustrating.

Thank you for your awesome work anyway.
Cheers.

**Comment by AdmiralCurtiss** [comment]
It would practically multiply all the work for each additional version supported, so no. Sorry. The only reason 1.4.1 and 1.4.2 are both supported is because they are for all intents and purposes identical -- only the game icon is different.

**Comment by zemanyak** [comment]
I understand, okay. I'm trying to avoid an audio bug (waiting time when transitioning to another BGM). I guess I'll just have not to keep pressing the turbo button. I read somewhere that it is hardware-related. Any chance I could fix it on my own ?

**Comment by AdmiralCurtiss** [comment]
I would really just update to 1.4.1...


If you *really* want to try to port the code, well, I hope you do know some x86 ASM. Here's the snippets I'm injecting:

https://github.com/AdmiralCurtiss/SenPatcher/blob/master/SenLib/Sen2/Sen2ExecutablePatches.BgmQueueingSoundThreadSide.cs
https://github.com/AdmiralCurtiss/SenPatcher/blob/master/SenLib/Sen2/music_queueing_sound_thread_side.asm

You'll also need to find the corresponding code and memory structures that I'm injecting into in the 1.3 executable.
