### ISSUE TITLE
CS3 Minor Text Issues

### ISSUE THREAD

**Issue by i-liek-katz** [AdmiralCurtiss/SenPatcher#70]
First, any mention of Hamilton refers to her as a man, despite being a woman. Not exactly NISA's fault since it was ambiguous until Kuro no Kiseki, and XSeed even went back and fixed their mentions of Hamilton. Some of the mentions are voiced, but the text could still be fixed.

Second, the quartz "Steel Bell", the SR/upgraded earth elemental bell quartz should say [(SR)Megalith Fall] instead of [(SR)Special], since it does grant the art, and the other SR/upgraded elemental bell quartz do say they grant their respective elemental arts.
![ed8_3_PC_0cZSza0oz4](https://user-images.githubusercontent.com/75770893/138574584-2a23c1ea-0db5-41d6-ad0d-254289dcd6a3.png)
![ed8_3_PC_MnpG9K89eF](https://user-images.githubusercontent.com/75770893/138574585-28893e27-726a-49a2-bebc-329e46078811.png)

**Comment by AdmiralCurtiss** [comment]
Hm, seems like the CS3 script format is somewhat different from CS1/2, that's annoying... I'll figure this out some other day...

**Comment by AdmiralCurtiss** [comment]
For reference:
https://trailsinthedatabase.com/game-scripts?fname=t0260&game_id=8#202
https://trailsinthedatabase.com/game-scripts?fname=f2000&game_id=8#48

**Comment by AdmiralCurtiss** [comment]
CS3 musings:
- textbox parsing function seems to be at 0x14030a890
- dispatcher is at 0x1403C7B40
- Opcode table is at 0x141A3C210, built at runtime like CS1/2, 16 bits per entry, first 8 are ptr to function
- Looks like 0x03 is still the unconditional jump and 0x09 the nop, but the textbox function is at 0x24 now (and 0x26 with no args is wait for user input...?).

**Comment by AdmiralCurtiss** [comment]
![20211231220432_1](https://user-images.githubusercontent.com/4522237/147839067-fd357370-6c2a-46db-9677-f00544e0cbc4.jpg)


The line from Schmidt later reads ambiguously to me whether he's referring to Hamilton (genuinely wondering what she's up to) or George (finding something suspicious about his claim), but I've changed it to 'she' for now as well.

**Comment by AdmiralCurtiss** [comment]
Fixed in [v0.8](https://github.com/AdmiralCurtiss/SenPatcher/releases/tag/v0.8).
