### ISSUE TITLE
CS2: Unused characters not leveling up properly after story beats

### ISSUE THREAD

**Issue by Lennyoh** [AdmiralCurtiss/SenPatcher#78]
After sections of the story where unused characters are supposed to automatically level up to a certain level to keep in line with everyone else such as after getting new batches of Class VII members in Act 1 or completing story sections of Act 2 like after saving Fiona, the characters remain the level they were at while Sen Patcher is used

**Comment by AdmiralCurtiss** [comment]
I can't even imagine what change could have possibly caused this, are you sure this is SenPatcher's fault? Do you have a save to test this with?

**Comment by Lennyoh** [comment]
To be honest, I think I might actually be misremembering when the game levels up unused characters. Testing save files without the patch is still giving me the same levels, and likewise checking online playthroughs so I think I just jumped the gun and the issue can be closed. My apologies!

**Comment by AdmiralCurtiss** [comment]
Well okay.
