### ISSUE TITLE
CS1: Arts Support link ability cutin doesn't show character model correctly.

### ISSUE THREAD

**Issue by AdmiralCurtiss** [AdmiralCurtiss/SenPatcher#8]
https://steamcommunity.com/app/538680/discussions/0/2275953283824357098/?tscn=1591096940#c2275953283837165196
> There's also another interesting bug that has been there in both games since the beginning if you feel like taking a crack at it. When someone casts arts, and is linked with a party member that has the "Arts Support" link ability, I think the viewport is completely messed up. On the PS3, a red texture appears on the right side of the screen, and it shows the character model of the character offering support. But on PC.. the character model is completely absent.
> https://i.imgur.com/bAIyb6H.jpg
> 
> I have no idea if it's possible to fix this or not. I do believe it was brought to Durante's attention, but I'm not sure if he ever attempted to fix it.

**Comment by AdmiralCurtiss** [comment]
PS3 reference footage:
https://www.youtube.com/watch?v=in0caJ-YlbE
https://www.youtube.com/watch?v=v1VFpGf3XyI

**Comment by AdmiralCurtiss** [comment]
The place to force this to always trigger here is at `0x688407`.

This seems to actually work, unlike the CS2 implementation, but still has the resolution != 1280x720 issues.

**Comment by AdmiralCurtiss** [comment]
Fixed in https://github.com/AdmiralCurtiss/SenPatcher/releases/tag/v0.8.2

**Comment by BigheadSMZ** [comment]
Oh wow! I check on the progress of this patcher from time to time, and I never expected this one to actually ever be fixed. Amazing work!
