### ISSUE TITLE
CS2 Steam: Occasional crash during turbo analyzing

### ISSUE THREAD

**Issue by Akonyl** [AdmiralCurtiss/SenPatcher#97]
Hi, dunno how active development on this is, but I've had three crashes in CS2 so far (CS2 PC v1.4.2, Senpatcher v0.8.1):
-once in act1 at the start with rean/toval
-once in a boss fight right before the intermission
-once during the intermission in a random enemy fight

The common thread here is that in all cases, I was holding the turbo button (using the senpatcher fix to disable the mid-battle-animation black-out during turbo) while analyzing the enemy, midway through the green reticle animation the game crashed. This happened both with battle scopes the first two times and with Analyze on the case during the intermission, but I've never seen it happen while using a Detector craft (which is how I analyze 90% of enemies), and I've analyzed every enemy I've come across (minus one or two). 

It doesn't happen every time a scope/analyze is used, though, so I can't be sure it's not just a coincidence it hasn't happened with Detector yet.

During the crash the game popped up a popup with a quick progress bar which would lead me to believe it was dumping a log somewhere, but I haven't been able to find anything. I found "CrashSender1403.exe", but no indication of any of the data it might have sent.

**Comment by AdmiralCurtiss** [comment]
Yeah, I've seen various complaints about this on the Steam forums, but I've never seen this crash myself so I'm unsure why it happens, which makes it a bit difficult to fix.

The crash reports are stored at `c:\Users\[username\AppData\Local\CrashRpt\` before they are sent, so maybe you can find some info there?

**Comment by Akonyl** [comment]
[UnsentCrashReports.zip](https://github.com/AdmiralCurtiss/SenPatcher/files/8420810/UnsentCrashReports.zip)

Got it, thanks. I zipped up+attached the UnsentCrashReports directory, which looks like it has all 3 crashes in it. Hopefully there's some useful info in there.

**Comment by AdmiralCurtiss** [comment]
Looks like it consistently crashes at `0x52e1ce` dereferencing a null pointer. That's something! I'll add a null check there and see if it changes anything.

**Comment by AdmiralCurtiss** [comment]
Okay, I'm not confident this is actually a proper fix (and it's a bit hard to test considering we don't know what triggers the bug in the first place), but try this:
[SenPatcher_v0.8.3_experimental-cs2-crash-fix.zip](https://github.com/AdmiralCurtiss/SenPatcher/files/8422623/SenPatcher_v0.8.3_experimental-cs2-crash-fix.zip)

Please report back with the results, regardless of if you encounter another crash or not.

**Comment by AdmiralCurtiss** [comment]
FYI, I think we're dealing with particle effects here, if I zero the relevant pointer manually (with my fix applied) some of them stop rendering.

**Comment by Akonyl** [comment]
Got it, I'll try it out. Is 0.8.3-dev on the title screen all that's needed to have the fix applied? I checked in the script/asset errors list and none of them seemed to obviously mention it, so I'm unsure if you just added it as a quick invisible/non-optional fix or what to just get it in for testing, just wanna make sure it applied.

I'll let you know what the result is, but since it took probably 20 hours in-game between the first two crashes (even if the other two were pretty close together), might be a while if I don't manage to hit the would-be trigger situation again.

**Comment by AdmiralCurtiss** [comment]
Yes, it's always on in that build, I didn't bother making a GUI option for it. If it says 0.8.3-dev you're good.

And yeah, take your time, no rush.

**Comment by Akonyl** [comment]
Update on this: Just finished the game, even buying a ton more battle scopes to use them primarily instead of Detector, and wasn't able to reproduce the crash. So unless my luck randomly got much better, the fix seems like it works, so thanks a lot for fixing that so quickly.


Also not really related, but since it's too minor to open yet another issue on it: I think this text box is supposed to say "_writhing_ deep within the abyss", not "writing deep within the abyss" 

![image](https://user-images.githubusercontent.com/3936176/163761910-cacc8f52-1009-431b-8d1e-597f48ee10c4.png)

**Comment by AdmiralCurtiss** [comment]
Not conclusive, but good to know, I'll include this as an option in the next release.

**Comment by AdmiralCurtiss** [comment]
It's been almost two years and I've never seen any complaint about this, so I think we can consider this fixed.
